services:
  user-mysql:
    image: mysql:8.0
    container_name: user-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      TZ: Asia/Shanghai
    ports:
      - "3308:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci

  user-redis:
    image: redis:7.2-alpine
    container_name: user-redis
    restart: unless-stopped
    ports:
      - "6381:6379"
    command: [ "redis-server", "--appendonly", "yes", "--requirepass", "123456" ]
    volumes:
      - ./redis-data:/data
